In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os
from zipfile import ZipFile
import time
from datetime import datetime
import itertools
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Conv2D, AveragePooling2D, GlobalAveragePooling2D, Dropout
from tensorflow.keras import utils 
from tensorflow.keras.callbacks import TensorBoard, ModelCheckpoint
import tensorflow_hub as hub
# Setting random seeds to reduce the amount of randomness in the neural net weights and results
# The results may still not be exactly reproducible
np.random.seed(42)
tf.random.set_seed(42)

2023-10-16 11:57:55.099105: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-16 11:57:55.277867: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-10-16 11:57:55.912173: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/larkinan/miniconda3/envs/tf/lib/python3.9/site-packages/cv2/../../lib

In [2]:
# Testing to ensure GPU is being utilized
# Ensure that the Runtime Type for this notebook is set to GPU
# If a GPU device is not found, change the runtime type under:
# Runtime>> Change runtime type>> Hardware accelerator>> GPU
# and run the notebook from the beginning again.

device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
    raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))


Found GPU at: /device:GPU:0


2023-10-16 11:57:56.816619: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-10-16 11:57:56.934557: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-10-16 11:57:56.934600: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-10-16 11:57:57.591290: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-10-16 11:57:57.591787: I tensorflow/compile

In [3]:
BATCH_SIZE = 64

def convertCodeToNumpy(code):
    encoding = []
    for charIndex in range(len(code)):
        curCar = code[charIndex]
        if curCar =='0':
            encoding.append(0)
        elif curCar =='1':
            encoding.append(1)
    return(encoding)

In [4]:
# Importing the augmented training dataset and testing dataset to create tensors of images using the filename paths.
train_aug_df = pd.read_csv("/mnt/h/Aspire/BERT/health/train/trainData.csv")
test_df = pd.read_csv("/mnt/h/Aspire/BERT/health/test/testData.csv")
train_aug_df['filename'] = train_aug_df['filename'].str.replace("H:/", "/mnt/h/", case = False)
train_aug_df['target'] = train_aug_df['encoding'].map(convertCodeToNumpy)
test_df['target'] = test_df['encoding'].map(convertCodeToNumpy)
test_df['filename'] = test_df['filename'].str.replace("H:/","/mnt/h/",case=False)
test_labels_list = list(test_df['target'])
print(train_aug_df.head())

                                            filename     encoding   
0  /mnt/h/Aspire/Bert/health/train/images/aug/3_4...  [0 0 0 0 0]  \
1  /mnt/h/Aspire/Bert/health/train/images/aug/3_4...  [0 0 0 0 0]   
2  /mnt/h/Aspire/Bert/health/train/images/aug/3_4...  [0 0 0 0 0]   
3  /mnt/h/Aspire/Bert/health/train/images/aug/3_4...  [0 0 0 0 0]   
4  /mnt/h/Aspire/Bert/health/train/images/aug/3_4...  [0 0 0 0 0]   

            target  
0  [0, 0, 0, 0, 0]  
1  [0, 0, 0, 0, 0]  
2  [0, 0, 0, 0, 0]  
3  [0, 0, 0, 0, 0]  
4  [0, 0, 0, 0, 0]  


In [5]:
# Defining a function to read the image, decode the image from given tensor and one-hot encode the image label class.
# Changing the channels para in tf.io.decode_jpeg from 3 to 1 changes the output images from RGB coloured to grayscale.
num_classes = 5
def _parse_function(filename, label):   
    image_string = tf.io.read_file(filename)
    image_decoded = tf.io.decode_jpeg(image_string, channels=3)    # channels=1 to convert to grayscale, channels=3 to convert to RGB.
    #image_decoded = tf.image.resize(image_decoded, [224, 224])
    image_decoded = tf.cast(image_decoded, dtype=tf.float32)
    
    return(image_decoded,label)

In [6]:
# Converting the filenames and target class labels into lists for augmented train and test datasets.
train_aug_filenames_list = list(train_aug_df['filename'])
train_aug_labels_list = list(train_aug_df['target'])
test_filenames_list = list(test_df['filename'])
test_labels_list = list(test_df['target'])
# Creating tensorflow constants of filenames and labels for augmented train and test datasets from the lists defined above.
train_aug_filenames_tensor = tf.constant(train_aug_filenames_list)
train_aug_labels_tensor = tf.constant(train_aug_labels_list)
test_filenames_tensor = tf.constant(test_filenames_list)
test_labels_tensor = tf.constant(test_labels_list)
test_dataset = tf.data.Dataset.from_tensor_slices((test_filenames_tensor, test_labels_tensor))
test_dataset = test_dataset.map(_parse_function)
# test_dataset = test_dataset.repeat(3)
test_dataset = test_dataset.batch(BATCH_SIZE)    # Same as batch_size hyperparameter in model.fit() below.

2023-10-16 11:57:57.937200: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-10-16 11:57:57.937272: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-10-16 11:57:57.937299: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-10-16 11:57:57.937732: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-10-16 11:57:57.937763: I tensorflow/compile

In [7]:
model = tf.keras.Sequential([
    #hub.KerasLayer("https://tfhub.dev/sayakpaul/vit_s16_fe/1", trainable=True),
    #hub.KerasLayer("https://tfhub.dev/sayakpaul/vit_b16_fe/1", trainable=True),
    #hub.KerasLayer("https://tfhub.dev/sayakpaul/vit_b32_fe/1", trainable=False),
     #hub.KerasLayer("https://tfhub.dev/sayakpaul/vit_r26_s32_lightaug_fe/1", trainable=True),
    #hub.KerasLayer("https://tfhub.dev/sayakpaul/vit_r50_l32_fe/1", trainable=True),
hub.KerasLayer("https://tfhub.dev/google/imagenet/resnet_v2_101/feature_vector/5",
               trainable=False, arguments=dict(batch_norm_momentum=0.997)),
    tf.keras.layers.Dense(100,activation='relu'),
    tf.keras.layers.Dense(5,activation='sigmoid')
])
model.compile(
    loss=[tf.keras.losses.BinaryCrossentropy(from_logits=True)],
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),metrics=['accuracy'])#,run_eagerly=True)
weightFile = "/mnt/h/Aspire/BERT/health/health_image_model_checkpoint.h5"
checkpoint = ModelCheckpoint(filepath=weightFile,
                                monitor='val_loss',
                                save_best_only=True,
                                save_weights_only=True,
                                verbose=1,
                                initial_value_threshold=  None#0.97828
                                )
model(np.zeros((1,224,224,3)))
if(os.path.exists(weightFile)):
    model.load_weights(weightFile)

Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089


Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089
2023-10-16 11:58:01.297800: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:428] Loaded cuDNN version 8500
2023-10-16 11:58:02.110686: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:630] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


In [8]:
# Generating predictions from the model above.
placeImagePred = model.predict(test_dataset)
#final_cnn_pred = final_cnn.predict(train_aug_dataset)
print(placeImagePred[0])
imgBinary = (placeImagePred>0.5)*1
print(np.max(placeImagePred,axis=0))

13/13 [==============================] - 2s 92ms/step
[0. 0. 1. 1. 0.]
[2.4412359e-01 1.0869887e-13 1.0000000e+00 1.0000000e+00 9.9998796e-01]


In [26]:
imgBinary[1]

array([0, 0, 0, 0, 0, 1, 0])

In [11]:
#BERT_pred = final_BERT.predict(testData)
def getPredictions(dataset,model):
    labelSet,predictions = [],[]
    for text, labels in dataset.take(1000):
        pred = model.predict(text)
        if(len(labelSet)==0):
            labelSet = labels.numpy()
            predictions = pred
        else:
            labelSet = np.concatenate((labelSet,labels))
            predictions = np.concatenate((predictions,pred))
    return([labelSet,predictions])
labels,predictions = getPredictions(test_dataset,placeImagePred)

AttributeError: 'numpy.ndarray' object has no attribute 'predict'

In [17]:
print(np.sum(test_labels_list,axis=0))
print(np.sum(imgBinary,axis=0))



[ 28 201 135 204 129]
[  0   0 779 645   1]


In [9]:
def calcTruePositive(labels,predictions):
    predictionsRound = tf.round(predictions)
    correct = np.multiply(labels,predictionsRound)
    nCorrect = np.sum(correct,axis=0)
    percCorrect = nCorrect/np.sum(labels,axis=0)*100
    return(nCorrect,percCorrect)
calcTruePositive(test_labels_list,placeImagePred)

(array([  0.,   0., 134., 171.,   0.]),
 array([ 0.        ,  0.        , 99.25925926, 83.82352941,  0.        ]))

In [10]:
test_labels_list = np.asarray(test_labels_list)
def calcTrueNegative(labels,predictions):
    predictionsRound = tf.round(predictions)
    labZeros = np.where(labels<1,1,0)
    predZeros = np.where(predictionsRound==0,1,0)
    correct = np.multiply(labZeros,predZeros)
    nCorrect = np.sum(correct,axis=0)
    percCorrect = nCorrect/np.sum(labZeros,axis=0)*100
    return(nCorrect,percCorrect)
calcTrueNegative(test_labels_list,placeImagePred)

(array([753, 580,   1, 103, 651]),
 array([100.        , 100.        ,   0.15479876,  17.85095321,
         99.84662577]))

In [11]:
def calcFalseNegative(labels,predictions):
    predictionsRound = tf.round(predictions)
    predZeros = np.where(predictionsRound==0,1,0)
    correct = np.multiply(labels,predZeros)
    nCorrect = np.sum(correct,axis=0)
    percCorrect = nCorrect/np.sum(labels,axis=0)*100
    return(nCorrect,percCorrect)
calcFalseNegative(test_labels_list,placeImagePred)

(array([ 28, 201,   1,  33, 129]),
 array([100.        , 100.        ,   0.74074074,  16.17647059,
        100.        ]))

In [12]:
def calcFalsePositive(labels,predictions):
    predictionsRound = tf.round(predictions)
    labZeros = np.where(labels==0,1,0)
    correct = np.multiply(labZeros,predictionsRound)
    nCorrect = np.sum(correct,axis=0)
    print(nCorrect)
    print(np.sum(labels,axis=0))
    percCorrect = nCorrect/np.sum(labels,axis=0)*100
    return(nCorrect,percCorrect)
calcFalsePositive(test_labels_list,placeImagePred)

[  0.   0. 645. 474.   1.]
[ 28 201 135 204 129]


(array([  0.,   0., 645., 474.,   1.]),
 array([  0.        ,   0.        , 477.77777778, 232.35294118,
          0.7751938 ]))

In [13]:
import pandas as ps
import os
allData = ps.read_csv("/mnt/h/Aspire/BERT/health/healthLabelsTrainTest_Oct3_23.csv")
testData = allData[allData['test']==1]
isImage = []
for curNum in range(testData.count()[0]):
    curRecord = testData.iloc[curNum]
    curImage = curRecord['img_http']
    if(os.path.exists("/mnt/h/Aspire/BERT/health/test/images/base/" + curImage[:-4] + "_padded.jpg")):
        isImage.append(1)
    else:
        isImage.append(0)
testData['isImage'] = isImage
imageTest = testData[testData['isImage']==1]
imageTest.to_csv('/mnt/h/Aspire/BERT/health/test/imageTweets.csv',index=False)

/tmp/ipykernel_41/3656412888.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testData['isImage'] = isImage


In [37]:
a = imageTest['text']
print(a)
tweetText = list(imageTest['text'])
tweetText = list(map(mapNewLineReplace,tweetText))
tweetLabels = list(map(convertPlaceCodeToLabels,list(imageTest['health_type'])))
tweetLabels2 = list(map(convertOutdoorCodeToLabels,list(imageTest['health_impact'])))
tweetLabels3 = np.concatenate((tweetLabels, tweetLabels2),axis=1)
print(tweetLabels3[0:10])
print(tweetLabels3[0:20])

4       @DBL_L_01 here is the version that @SwainEvent...
6       Tonight I parted ways with my good friend, my ...
11        @Ash_Tree_Lane cough hey http://t.co/8KRUqUB9YQ
18      3+ hours &amp; counting on runway,planning nut...
28      my face when I met @chescaleigh 😍 thank you an...
                              ...                        
4969    The 2019 Top Dog Tournament to benefit the Leu...
4974    @EmerickGiveBack Portland's Emergency Coordina...
4976    Learning a lot @SACocktailConf http://t.co/zCQ...
4977    The imagination of children. #pirates #bubbles...
4989    Just found out me and Tyus went to preschool t...
Name: text, Length: 781, dtype: object
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 1]
 [0 1 1 0 1]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 

In [19]:
# Import dependencies
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os
from zipfile import ZipFile
import time
from datetime import datetime
import itertools
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Conv2D, AveragePooling2D, GlobalAveragePooling2D, Dropout
from tensorflow.keras import utils 
from tensorflow.keras.callbacks import TensorBoard, ModelCheckpoint
import glob

# Setting random seeds to reduce the amount of randomness in the neural net weights and results
# The results may still not be exactly reproducible
np.random.seed(42)
tf.random.set_seed(42)
import tensorflow as tf
import os
import glob
import numpy as np
from transformers import BertTokenizer, TFBertForMaskedLM
from keras.callbacks import ModelCheckpoint
from transformers import *
import transformers
import keras
import shutil
import time


/home/larkinan/miniconda3/envs/tf/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
/home/larkinan/miniconda3/envs/tf/lib/python3.9/site-packages/transformers/generation_utils.py:24: FutureWarning: Importing `GenerationMixin` from `src/transformers/generation_utils.py` is deprecated and will be removed in Transformers v5. Import as `from transformers import GenerationMixin` instead.
  warnings.warn(
/home/larkinan/miniconda3/envs/tf/lib/python3.9/site-packages/transformers/generation_tf_utils.py:24: FutureWarning: Importing `TFGenerationMixin` from `src/transformers/generation_tf_utils.py` is deprecated and will be removed in Transformers v5. Import as `from transformers import TFGenerationMixin` instead.
  warnings.warn(
Loading custom CUDA kernels...
Xformers is not installed correctly. If 

ninja: no work to do.


In [15]:
def mapNewLineReplace(origLine):
    newLine = origLine.replace("\n",". ")
    return(newLine)

In [20]:
def setupModelInputs(tweetData,debug=False):
    tweetText = list(tweetData['text'])
    tweetText = list(map(mapNewLineReplace,tweetText))
    inputs = TOKEN(tweetText,max_length=100,truncation=True,padding='max_length',return_tensors="tf")
    inp_ids = tf.convert_to_tensor(inputs['input_ids'])
    inputs['input_ids'] = inp_ids
    return(inputs)

In [22]:
#modelFile = '/mnt/h/Aspire/BERT/child/checkpiont_3layers/age_model_checkpoint.h5'
modelFile = '/mnt/h/Aspire/BERT/health/health_model_checkpoint.h5'
final_BERT = tf.keras.models.load_model(modelFile,custom_objects={"TFBertModel": transformers.TFBertModel})
final_BERT.compile(loss=[tf.keras.losses.BinaryCrossentropy()],optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),metrics=['accuracy'])

Model config BertConfig {
  "_name_or_path": "/mnt/h/Aspire/BERT/testSaveBERT",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.33.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30623
}



In [23]:
TOKEN = BertTokenizer.from_pretrained('expandedTokenBase')
b = setupModelInputs(imageTest)
preds = final_BERT.predict([b['input_ids'],b['attention_mask']])
predsInt = (preds>0)*1
print(predsInt)

loading file vocab.txt
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
Adding 😂 to the vocabulary
Adding ❤ to the vocabulary
Adding 😭 to the vocabulary
Adding 😍 to the vocabulary
Adding 🎉 to the vocabulary
Adding 😊 to the vocabulary
Adding 😘 to the vocabulary
Adding 😩 to the vocabulary
Adding 💕 to the vocabulary
Adding 🏽 to the vocabulary
Adding 🏼 to the vocabulary
Adding 🏾 to the vocabulary
Adding 💯 to the vocabulary
Adding 🔥 to the vocabulary
Adding 🏻 to the vocabulary
Adding 🙏 to the vocabulary
Adding 🙌 to the vocabulary
Adding 🤣 to the vocabulary
Adding 😒 to the vocabulary
Adding 💙 to the vocabulary
Adding ♀ to the vocabulary
Adding 🙄 to the vocabulary
Adding 😁 to the vocabulary
Adding 👏 to the vocabulary
Adding ☺ to the vocabulary
Adding 💀 to the vocabulary
Adding 👌 to the vocabulary
Adding 🎈 to the vocabulary
Adding 💜 to the vocabulary
Adding 💗 to the vocabulary
Adding 😅 to the vocabulary
Adding 💖 to the vocabulary
Adding 🤔 t

25/25 [==============================] - 2s 38ms/step
[[0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 ...
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]]


In [53]:
print(np.sum(predsInt,axis=1))

[1 0 2 0 0 1 2 1 1 1 2 1 2 1 2 2 0 2 1 2 1 1 1 2 1 1 0 2 0 1 1 2 1 1 2 1 2
 0 2 1 0 2 1 0 1 1 2 0 1 1 1 2 0 1 0 2 0 1 0 2 2 0 1 2 1 2 1 0 0 1 1 2 2 2
 0 2 0 2 2 0 1 2 2 2 2 0 2 1 2 0 0 1 2 1 2 1 0 0 2 0 2 1 1 2 2 0 1 2 2 1 1
 1 1 1 1 2 2 2 1 1 1 1 2 1 1 1 2 2 1 2 2 1 1 2 1 1 2 2 2 1 2 2 0 1 1 1 2 2
 1 0 1 0 2 0 1 1 1 1 2 2 1 2 2 0 2 1 1 1 0 2 2 1 1 1 2 0 0 1 0 1 1 0 1 1 1
 2 0 2 0 0 1 1 1 1 0 1 2 1 2 1 2 1 0 0 1 0 0 2 0 1 0 0 1 2 2 1 1 1 0 2 0 1
 2 2 2 2 0 2 0 1 2 1 1 2 2 0 2 1 1 2 1 0 2 1 1 1 2 2 0 2 1 1 0 1 2 0 1 2 2
 2 2 2 1 1 2 2 0 2 0 2 2 2 1 1 0 2 1 2 1 1 0 0 0 0 1 2 1 2 1 1 2 1 1 2 0 1
 1 0 2 1 1 1 0 2 1 1 1 0 2 2 0 2 1 1 0 1 1 2 1 1 2 2 1 2 2 2 2 1 0 1 1 3 1
 2 1 1 1 2 2 2 1 2 0 1 1 1 2 0 0 2 1 2 1 0 1 0 2 0 2 0 1 2 0 2 0 2 1 0 2 1
 2 1 1 1 2 0 1 2 2 1 2 1 1 0 0 1 1 1 2 1 2 0 0 0 2 2 0 1 2 2 1 0 1 0 0 1 2
 0 0 0 1 0 0 2 1 2 3 0 2 1 2 2 2 0 2 0 0 0 1 0 2 1 2 1 2 0 0 1 0 2 1 2 0 2
 2 2 2 1 1 2 0 0 2 2 0 2 1 0 2 0 1 1 2 2 2 1 2 0 1 2 1 1 2 0 1 1 1 1 2 2 0
 2 2 1 2 1 2 0 1 0 2 2 0 

In [36]:
healthCodingDict = {
            'Cognitive health':0,
            'Emotional/social health':1,
            'Physical health':2,
            'Positive impact':0,
            'Negative impact':1,
        }

def convertPlaceCodeToLabels(placeCode):
    keys = list(healthCodingDict.keys())
    codeArr = [0 for x in range(3)]
    for key in keys:
        if key in placeCode:
            codeArr[healthCodingDict[key]] = 1
    return(np.asarray(codeArr))
    
def convertOutdoorCodeToLabels(outdoorCode):
    keys = list(healthCodingDict.keys())
    codeArr = [0 for x in range(2)]
    for key in keys:
        if key in outdoorCode:
            codeArr[healthCodingDict[key]] = 1
    return(np.asarray(codeArr))

In [38]:
def calcTruePositive(labels,predictions):
    correct = np.multiply(labels,predictions)
    nCorrect = np.sum(correct,axis=0)
    percCorrect = nCorrect/np.sum(labels,axis=0)*100
    return(nCorrect,percCorrect)
calcTruePositive(tweetLabels3,predsInt)

(array([  4,  72, 100,  87,  88]),
 array([14.28571429, 35.82089552, 74.07407407, 42.64705882, 68.21705426]))

In [39]:
def calcTrueNegative(labels,predictions):
    labZeros = np.where(labels==0,1,0)
    predZeros = np.where(predictions==0,1,0)
    correct = np.multiply(labZeros,predZeros)
    nCorrect = np.sum(correct,axis=0)
    percCorrect = nCorrect/np.sum(labZeros,axis=0)*100
    return(nCorrect,percCorrect)
calcTrueNegative(tweetLabels3,predsInt)

(array([749, 538, 617, 533, 610]),
 array([99.4687915 , 92.75862069, 95.51083591, 92.37435009, 93.55828221]))

In [40]:
def calcFalsePositive(labels,predictions):
    labZeros = np.where(labels==0,1,0)
    correct = np.multiply(labZeros,predictions)
    nCorrect = np.sum(correct,axis=0)
    print(nCorrect)
    percCorrect = nCorrect/np.sum(labels,axis=0)*100
    return(nCorrect,percCorrect)
calcFalsePositive(tweetLabels3,predsInt)

[ 4 42 29 44 42]


(array([ 4, 42, 29, 44, 42]),
 array([14.28571429, 20.89552239, 21.48148148, 21.56862745, 32.55813953]))

In [41]:
def calcFalseNegative(labels,predictions):
    predZeros = np.where(predictions==0,1,0)
    correct = np.multiply(labels,predZeros)
    nCorrect = np.sum(correct,axis=0)
    percCorrect = nCorrect/np.sum(labels,axis=0)*100
    return(nCorrect,percCorrect)
calcFalseNegative(tweetLabels3,predsInt)

(array([ 24, 129,  35, 117,  41]),
 array([85.71428571, 64.17910448, 25.92592593, 57.35294118, 31.78294574]))